### ISSUE TITLE
Added OnEndReached and getting Error: Rendered more hooks than during the previous render.

### ISSUE THREAD

**Issue by jsonpreet** [Mindinventory/react-native-stagger-view#6]
https://github.com/jsonpreet/pinsta-app/blob/master/app/(app)/index.tsx

**Comment by PremshankarMI** [comment]
Thank you @jsonpreet for addressing this issue.

![Screenshot 2023-04-10 at 6 09 18 PM](https://user-images.githubusercontent.com/104554054/230903787-d90d28c0-e3d6-4d43-9970-64f047629504.png)

The problem with the renderItem prop. Specifically, it appears that passing a component as a function to renderItem is causing the state to not be properly recycled.

To solve this issue, you can try passing the component as a return value in the renderItem function instead. This should help ensure that the state is properly recycled.

Rather than being passed as a function directly. This should help ensure that the state is properly recycled, and hopefully solve the issue you're experiencing.

**Comment by jsonpreet** [comment]
@PremshankarMI 

Thank You for Support!
